version: '3.8'
services:
  web:
    container_name: web
    image: registry.digitalocean.com/linkerry/web:latest
    ports:
      - ${VIRTUAL_PORT}:${VIRTUAL_PORT}
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=anteqkois@gmail.com
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK:-proxy}
