version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./
      cache_from:
        - linkerry/base:latest
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: web:latest
    env_file:
      - ../../.env
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'production'
    # networks:
    #   - proxy
    restart: on-failure

# networks:
#   proxy:
#     driver: bridge
