import { ThemeProvider } from '@market-connector/ui-components'
import 'tailwindcss/tailwind.css'
import './global.css'

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
