import { ConnectorAuth, Validators } from "@linkerry/connectors-framework"
import { BinanceClient } from "./client"

const authDescription = `
Follow Binance tutorial to get API Keys for your account, then fill form:
tutorial: https://www.binance.com/en/support/faq/how-to-create-api-keys-on-binance-360002502072
`

export const binanceAuth = ConnectorAuth.CustomAuth({
	description: authDescription,
	required: true,
	props: {
		apiKey: ConnectorAuth.SecretText({
			displayName: 'API Key',
			description: 'API Key generated by Binance',
			required: true,
			validators: [Validators.string],
		}),
		secretKey: ConnectorAuth.SecretText({
			displayName: 'Secret Key',
			description: 'Secret Key generated by Binance',
			required: true,
			validators: [Validators.string],
		}),
	},
	validate: async ({ auth }) => {
		BinanceClient.setAuth(auth)

		try {
			BinanceClient.exchange.checkRequiredCredentials()
		} catch (error) {
			console.log(error)
			return {
				valid: false,
				error: 'Missing API keys',
			}
		}

		try {
			await BinanceClient.exchange.loadMarkets()
			const balance = await BinanceClient.exchange.fetchBalance()
			if (balance.info.balances.length)
				return {
					valid: true,
				}
		} catch (error) {
			return {
				valid: false,
				error: 'Invalid API keys',
			}
		}

		return {
			valid: false,
			error:'Can not verify your API keys. Inform out IT team'
		}
	},
})
