# path to a directory with all packages
storage: ../tmp/local-registry/storage

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1

security:
  api:
    jwt:
      sign:
        expiresIn: 365d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

packages:
  '@linkerry/*':
    access: $authenticated
    publish: $authenticated
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  # '@linkerry/*':
  #   # scoped packages
  #   # you can specify usernames/groupnames (depending on your auth plugin)
  #   # and three keywords: "$all", "$anonymous", "$authenticated"
  #   access: '$authenticated'
  #   publish: '$authenticated'
  # '**':
  #   proxy: npmjs
  #   access: '$authenticated'
  #   publish: '$authenticated'
  # # '**':
  # #   # give all users (including non-authenticated users) full access
  # #   # because it is a local registry
  # #   access: $all
  # #   publish: $all
  # #   unpublish: $all

  # #   # if package is not available locally, proxy requests to npm registry
  # #   proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true # set offline to true to allow publish offline
