services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - ${VIRTUAL_PORT}:${VIRTUAL_PORT}
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VERDACCIO_PORT=4873
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
