services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - ${VIRTUAL_PORT}:${VIRTUAL_PORT}
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=anteqkois@gmail.com
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VERDACCIO_APPDIR=/verdaccio/conf
      - VERDACCIO_PORT=4873
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'

volumes:
  verdaccio:
    driver: local

networks:
  default:
    external:
      name: ${NETWORK:-proxy}
