import { ConnectorAuth } from '@linkerry/connectors-framework'
import { KucoinClient } from './client'

const authDescription = `

1. Go to [account dashboard](https://www.kucoin.com/account).
2. Select on the left menu **API Management**.
3. Click button **Create API**.
4. Choose **API-Based Trading** tab.
5. Fill form* and generate API Keys, remember to hold generated password.
6. Congratulations! You have generated your API Keys.

*Set **IP restriction** to "No" (our flows runs on multiple servers). Remember to unlock the restrictions that you will use. So if you want to trade, unlock **Spot Trading** and similarly for other options.
`

export const kucoinAuth = ConnectorAuth.CustomAuth({
  description: authDescription,
  required: true,
  props: {
    apiKey: ConnectorAuth.SecretText({
      displayName: 'Key',
      description: 'Key generated by Exchange',
      required: true,
    }),
    secretKey: ConnectorAuth.SecretText({
      displayName: 'Secret Key',
      description: 'Secret Key generated by Exchange',
      required: true,
    }),
    password: ConnectorAuth.SecretText({
      displayName: 'Password',
      description: 'Password generated by You',
      required: true,
    }),
  },
  validate: async ({ auth }) => {
    KucoinClient.setAuth(auth)

    try {
      KucoinClient.exchange.checkRequiredCredentials()
    } catch (error) {
      console.error(error)
      return {
        valid: false,
        error: 'Missing API keys',
      }
    }

    try {
      await KucoinClient.exchange.loadMarkets()
      const balance = await KucoinClient.exchange.fetchBalance()
      if (balance.info.balances.length)
        return {
          valid: true,
        }
    } catch (error) {
      return {
        valid: false,
        error: 'Invalid API keys',
      }
    }

    return {
      valid: false,
      error: 'Can not verify your API keys. Inform out Team',
    }
  },
})
