export enum WEBSOCKET_EVENT {
  EXCEPTION = 'exception',
  TEST_FLOW = 'TEST_FLOW',
  TEST_FLOW_STARTED = 'TEST_FLOW_STARTED',
  TEST_FLOW_FINISHED = 'TEST_FLOW_FINISHED',
  WATCH_WEBHOOK_TRIGGER_EVENTS = 'WATCH_WEBHOOK_TRIGGER_EVENTS',
  WATCH_WEBHOOK_TRIGGER_EVENTS_RESPONSE = 'WATCH_WEBHOOK_TRIGGER_EVENTS_RESPONSE',
  WEBHOOK_TRIGGER_EVENTS_STARTED = 'WEBHOOK_TRIGGER_EVENTS_STARTED',
  CANCEL_WEBHOOK_WATCHER = 'CANCEL_WEBHOOK_WATCHER',
  WEBHOOK_WATCHER_CANCELED = 'WEBHOOK_WATCHER_CANCELED',
}

export enum WEBSOCKET_NAMESPACE {
  FLOW_RUNS = 'FLOW_RUNS',
  TRIGGER_EVENTS = 'TRIGGER_EVENTS',
}
