export const connectorTag = [
  'cryptocurrency',
  'trading',
  'alerts',
  'exchange',
  'data feed',
  'stock market',
  'chart',
  'core',
  'time',
  'plan',
  'connector',
  'trends',
  'office',
  'collaboration',
  'data management',
  'communication',
  'bots',
  'community management',
  'payments',
  'commerce',
  'artificial intelligence',
] as const
export type ConnectorTag = (typeof connectorTag)[number]
