import { ConnectorAuth } from '@linkerry/connectors-framework'
import { MexcClient } from './client'

const authDescription = `

1. Go to [account dashboard](https://www.mexc.com/user).
2. Select on the left menu **API Management**.
3. Select necessary options for API keys like **Trade** etc..
4. Don't fill IP Adress (our flows runs on multiple servers).
6. Congratulations! You have generated your API Keys.
`

export const mexcAuth = ConnectorAuth.CustomAuth({
  description: authDescription,
  required: true,
  props: {
    access_key: ConnectorAuth.SecretText({
      displayName: 'Access Key',
      description: 'Access Key generated by Exchange',
      required: true,
    }),
    secret_key: ConnectorAuth.SecretText({
      displayName: 'Secret Key',
      description: 'Secret Key generated by Exchange',
      required: true,
    }),
  },
  validate: async ({ auth }) => {
    MexcClient.setAuth(auth)

    try {
      MexcClient.exchange.checkRequiredCredentials()
    } catch (error) {
      console.error(error)
      return {
        valid: false,
        error: 'Missing API keys',
      }
    }

    try {
      await MexcClient.exchange.loadMarkets()
      const balance = await MexcClient.exchange.fetchBalance()
      if (balance.info.balances.length)
        return {
          valid: true,
        }
    } catch (error) {
      return {
        valid: false,
        error: 'Invalid API keys',
      }
    }

    return {
      valid: false,
      error: 'Can not verify your API keys. Inform out Team',
    }
  },
})
