services:
  api-gateway:
    container_name: api-gateway
    image: registry.digitalocean.com/linkerry/api-gateway:latest
    ports:
      - ${PORT_API_GATEWAY}:${PORT_API_GATEWAY}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=anteqkois@gmail.com
      - VIRTUAL_PORT=${PORT_API_GATEWAY}
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./.env:/app/.env
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
    command: redis-server --appendonly yes --replica-read-only no --bind redis --port 6379 --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      # for no reason this don't work if i change port
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local

networks:
  default:
    external:
      name: ${NETWORK:-proxy}
