version: '3.8'

services:
  api-gateway:
    image: registry.digitalocean.com/linkerry/api-gateway:latest
    ports:
      - ${VIRTUAL_PORT}:${VIRTUAL_PORT}
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=anteqkois@gmail.com
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
    command: redis-server --appendonly yes --replica-read-only no --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    restart: always
    ports:
      - 4004:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local

# networks:
#   default:
#     external:
#       name: ${NETWORK:-proxy}
