import { ConnectorAuth } from '@linkerry/connectors-framework'
import { ExchangeClientInterface } from '../types'

export const exchangeAuth = (exchangeClient: ExchangeClientInterface, authDescription: string) =>
  ConnectorAuth.CustomAuth({
    description: authDescription,
    required: true,
    props: {
      api_key: ConnectorAuth.SecretText({
        displayName: 'API Key',
        description: 'API Key generated by Exchange',
        required: true,
      }),
      secret_key: ConnectorAuth.SecretText({
        displayName: 'Secret Key',
        description: 'Secret Key generated by Exchange',
        required: true,
      }),
    },
    validate: async ({ auth }) => {
      exchangeClient.setAuth(auth)

      try {
        exchangeClient.exchange.checkRequiredCredentials()
      } catch (error) {
        console.error(error)
        return {
          valid: false,
          error: 'Missing API keys',
        }
      }

      try {
        await exchangeClient.exchange.fetchBalance()
        return {
          valid: true,
        }
      } catch (error) {
        return {
          valid: false,
          error: 'Invalid API keys',
        }
      }
    },
  })
