name: build-and-deploy-api-gateway

on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build images
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: pnpm install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('package.json') }}
      - name: Build base image
        run: npm run docker-base
      - name: Tag base image
        run: docker tag linkerry/base registry.digitalocean.com/linkerry/base:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/linkerry/base:latest
      - name: Build image for web
        env:
          NEXT_TELEMETRY_DISABLED: true
          NEXT_PUBLIC_API_HOST: https://api.linkerry.com
        run: docker build -t linkerry/api-gateway --build-arg NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST -f ./apps/api-gateway/Dockerfile . --platform=linux/amd64
      - name: Tag web image
        run: docker tag linkerry/api-gateway registry.digitalocean.com/linkerry/api-gateway:latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/linkerry/api-gateway:latest
