name: test-ssh

on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to DigitalOcean VPS and run commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: root
        key: ${{ secrets.SSH_PASSPHRASE_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        script: |
          echo "Connected to VPS"
          uptime
          touch test.txt
